<a href="https://colab.research.google.com/github/mdkhanga/ai-tools/blob/main/testpytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [4]:
x = torch.arange(12, dtype=torch.float32)

In [6]:
x


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
x.numel()

12

In [10]:
X=x.reshape(3,4)
print(X)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [12]:
torch.zeros((2,3,4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones((2,3,4))


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [17]:
torch.randn(3,4)


tensor([[ 5.7184e-01, -1.1978e+00,  7.6243e-01,  4.1242e-04],
        [-1.4945e+00, -7.2863e-01, -1.8852e-02,  7.8195e-01],
        [ 9.6821e-01, -1.5740e-01,  3.1918e-01, -4.6856e-01]])